cloud-init: fix missing pyserial dependency
and check for all required imports as per requirements.txt

While debugging missing metadata in the cloud-init boot local phase
in a NixOS VM on SmartOS, the following error was observed:
SystemError: Unable to open /dev/ttyS1
Adding the missing pyserial dependency fixes the above error and
cloud-init metadata detection now works in NixOS VMs on SmartOS

(cherry picked from commit cf594d1f6e2dc1beea416d007b70c38a5e54ba7f)