nixos/soju: add defaults and assertions for TLS
Enabling soju without providing a value for tlsCertificate currently
results in:

  error: The option `services.soju.tlsCertificate' is used but not
  defined.

Since tlsCertificate is intended to be optional, set default to null.

Additionally, add assertions to ensure that both tlsCertificate and
tlsCertificateKey are either set or unset.

(cherry picked from commit 5c0e18a6bb553e692f276b7dafcd8058d5460046)